version: 2
jobs:
  build:
    working_directory: ~/responsive-analog-read
    docker:
      - image: circleci/node:10-stretch

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "docs/yarn.lock" }}
            - v1-dependencies-
      - run: cd docs && yarn && yarn install-emcc
      - save_cache:
          paths:
            - docs/node_modules
            - docs/emsdk-portable.tar.gz
            - docs/emsdk-portable
          key: v1-dependencies-{{ checksum "docs/yarn.lock" }}

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ] || [ "${CIRCLE_BRANCH}" == "release/version-2" ]; then
              git config --global -l && git config --global user.email circleci@circleci && git config --global user.name CircleCI && cd docs && yarn deploy
            fi

